/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.vehicle_code.JPanels;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class Pnl_VehicleAreaOp extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_VehicleAreaOp
     */
    /*ESTE PANEL TIENE EL OBJETIVO DE QUE EN LOS COMBO BOX SE MUESTRE INFORMACIÓN PREDETERMINADA; Y CUANDO SELECCIONES 
    ALGUNA OPCIÓN DE INFORMACIÓN DE ESTOS; SE HARÁN PARTE DEL OBJETO VEHICULO QUE SE ESTÁ CREANDO. POR PARTE DE LOS CAMPOS
    DE TEXTO, SE NECESITA QUE SEAN RELLENADOS PARA COMPLETAR LA INFORMACIÓN DEL OBJETO*/
    
    //SE TIENE QUE ENCONTRAR FORMAS DE VALIDAR LO QUE SE ESCRIBE[PENDIENTE]
    //
    
    
    
    //ACLARACIÓN DEL POR QUÉ SOLO HAY GETTERS AND SETTERS
    //
    //NECESITO CREAR CONTROLLERS, ESOS SON LOS PINCELES PARA PODER TRABAJAR; MIENTRAS QUE AQUÍ; SOLO SE USA LA HOJA, O SEA; 
    //ELLOS SON EL LÁPIZ Y AQUÍ LA HOJA PARA PRESENTAR LA INFO
    
    //Necesito crear "Gettters and Setters", para presentar la información a través de los campos de texto;
    //combo box, y spinners.
    //(RECORDAR HACER UN GRUPO PARA LOS RADIO BUTTONS [YA HECHO]
    public Pnl_VehicleAreaOp() {
        initComponents();
    }

    public JSpinner getSpn_Price() {
        return Spn_Price;
    }

    public void setSpn_Price(JSpinner Spn_Price) {
        this.Spn_Price = Spn_Price;
    }

    public ButtonGroup getBtng_Transmission() {
        return btng_Transmission;
    }

    public void setBtng_Transmission(ButtonGroup btng_Transmission) {
        this.btng_Transmission = btng_Transmission;
    }

    public JComboBox<String> getCmb_EColor() {
        return cmb_EColor;
    }

    public void setCmb_EColor(JComboBox<String> cmb_EColor) {
        this.cmb_EColor = cmb_EColor;
    }

    public JComboBox<String> getCmb_IColor() {
        return cmb_IColor;
    }

    public void setCmb_IColor(JComboBox<String> cmb_IColor) {
        this.cmb_IColor = cmb_IColor;
    }

    public JComboBox<String> getCmb_Make() {
        return cmb_Make;
    }

    public void setCmb_Make(JComboBox<String> cmb_Make) {
        this.cmb_Make = cmb_Make;
    }

    public JComboBox<String> getCmb_Model() {
        return cmb_Model;
    }

    public void setCmb_Model(JComboBox<String> cmb_Model) {
        this.cmb_Model = cmb_Model;
    }

    public JComboBox<String> getCmb_Status() {
        return cmb_Status;
    }

    public void setCmb_Status(JComboBox<String> cmb_Status) {
        this.cmb_Status = cmb_Status;
    }

    public JComboBox<String> getCmb_Year() {
        return cmb_Year;
    }

    public void setCmb_Year(JComboBox<String> cmb_Year) {
        this.cmb_Year = cmb_Year;
    }

    public JTextField getFrmt_VIN() {
        return frmt_VIN;
    }

    public void setFrmt_VIN(JTextField frmt_VIN) {
        this.frmt_VIN = frmt_VIN;
    }

    public JButton getBtn_Browse() {
        return btn_Browse;
    }

    public void setBtn_Browse(JButton btn_Browse) {
        this.btn_Browse = btn_Browse;
    }

    public JRadioButton getRbtn_Auto() {
        return rbtn_Auto;
    }

    public void setRbtn_Auto(JRadioButton rbtn_Auto) {
        this.rbtn_Auto = rbtn_Auto;
    }

    public JRadioButton getRbtn_Manual() {
        return rbtn_Manual;
    }

    public void setRbtn_Manual(JRadioButton rbtn_Manual) {
        this.rbtn_Manual = rbtn_Manual;
    }

    public JSpinner getSpn_Miles() {
        return spn_Miles;
    }

    public void setSpn_Miles(JSpinner spn_Miles) {
        this.spn_Miles = spn_Miles;
    }

    public JTextField getTxt_Engine() {
        return txt_Engine;
    }

    public void setTxt_Engine(JTextField txt_Engine) {
        this.txt_Engine = txt_Engine;
    }

    public JTextField getTxt_Image() {
        return txt_Image;
    }

    public void setTxt_Image(JTextField txt_Image) {
        this.txt_Image = txt_Image;
    }

    public JTextField getTxt_Stock() {
        return txt_Stock;
    }

    public void setTxt_Stock(JTextField txt_Stock) {
        this.txt_Stock = txt_Stock;
    }

    public JTextField getTxt_Style() {
        return txt_Style;
    }

    
    public void setTxt_Style(JTextField txt_Style) {    
        this.txt_Style = txt_Style;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btng_Transmission = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_Stock = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmb_Year = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmb_Make = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmb_Model = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txt_Style = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        frmt_VIN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmb_EColor = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmb_IColor = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        spn_Miles = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        Spn_Price = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        rbtn_Auto = new javax.swing.JRadioButton();
        rbtn_Manual = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txt_Engine = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_Image = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmb_Status = new javax.swing.JComboBox<>();
        btn_Browse = new javax.swing.JButton();
        btn_Save = new javax.swing.JButton();
        btn_Cancel = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("StockNumber=>");
        jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        txt_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_StockActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(txt_Stock, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Year:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(cmb_Year, gridBagConstraints);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Make:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(cmb_Make, gridBagConstraints);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Model:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jLabel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(cmb_Model, gridBagConstraints);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Style:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(txt_Style, gridBagConstraints);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("VIN:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(frmt_VIN, gridBagConstraints);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Exterior Color:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jLabel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(cmb_EColor, gridBagConstraints);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Interior Color:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jLabel8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(cmb_IColor, gridBagConstraints);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Miles:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jLabel9, gridBagConstraints);

        spn_Miles.setModel(new javax.swing.SpinnerNumberModel(0L, null, null, 1L));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(spn_Miles, gridBagConstraints);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Price:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jLabel10, gridBagConstraints);

        Spn_Price.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(Spn_Price, gridBagConstraints);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Transmission:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jLabel14, gridBagConstraints);

        btng_Transmission.add(rbtn_Auto);
        rbtn_Auto.setSelected(true);
        rbtn_Auto.setText("Automatic");
        rbtn_Auto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_AutoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(rbtn_Auto, gridBagConstraints);

        btng_Transmission.add(rbtn_Manual);
        rbtn_Manual.setText("Manual");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(rbtn_Manual, gridBagConstraints);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Engine:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jLabel11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(txt_Engine, gridBagConstraints);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Image Path:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jLabel12, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(txt_Image, gridBagConstraints);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Status:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jLabel13, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(cmb_Status, gridBagConstraints);

        btn_Browse.setText("Browse");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(btn_Browse, gridBagConstraints);

        btn_Save.setText("Save");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        jPanel1.add(btn_Save, gridBagConstraints);

        btn_Cancel.setText("Cancel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        jPanel1.add(btn_Cancel, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtn_Cancel() {
        return btn_Cancel;
    }

    public void setBtn_Cancel(JButton btn_Cancel) {
        this.btn_Cancel = btn_Cancel;
    }

    public JButton getBtn_Save() {
        return btn_Save;
    }

    public void setBtn_Save(JButton btn_Save) {
        this.btn_Save = btn_Save;
    }

    private void txt_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_StockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_StockActionPerformed

    private void rbtn_AutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_AutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_AutoActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Spn_Price;
    private javax.swing.JButton btn_Browse;
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Save;
    private javax.swing.ButtonGroup btng_Transmission;
    private javax.swing.JComboBox<String> cmb_EColor;
    private javax.swing.JComboBox<String> cmb_IColor;
    private javax.swing.JComboBox<String> cmb_Make;
    private javax.swing.JComboBox<String> cmb_Model;
    private javax.swing.JComboBox<String> cmb_Status;
    private javax.swing.JComboBox<String> cmb_Year;
    private javax.swing.JTextField frmt_VIN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtn_Auto;
    private javax.swing.JRadioButton rbtn_Manual;
    private javax.swing.JSpinner spn_Miles;
    private javax.swing.JTextField txt_Engine;
    private javax.swing.JTextField txt_Image;
    private javax.swing.JTextField txt_Stock;
    private javax.swing.JTextField txt_Style;
    // End of variables declaration//GEN-END:variables
}
