package com.mycompany.vehicle_code.JFrames;

import com.mycompany.vehicle_code.JPanels.Pnl_VehicleAreaOp;
import java.awt.BorderLayout;
import javax.swing.JComponent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class Frm_VehicleApp_main extends javax.swing.JFrame {

    private Pnl_VehicleAreaOp pnl_VehicleAreaOp; //Necesito crear o declarar como se irá llamando este objeto
    /**
     * Creates new form Frm_VehicleApp_main
     */
    public Frm_VehicleApp_main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_SubContainer = new javax.swing.JPanel();
        btn_New = new javax.swing.JButton();
        btn_Search = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        Pnl_MainContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pnl_SubContainer.setLayout(new java.awt.GridLayout(5, 1));

        btn_New.setText("New");
        btn_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewActionPerformed(evt);
            }
        });
        Pnl_SubContainer.add(btn_New);

        btn_Search.setText("Search");
        Pnl_SubContainer.add(btn_Search);

        btn_Exit.setText("Exit");
        Pnl_SubContainer.add(btn_Exit);

        getContentPane().add(Pnl_SubContainer, java.awt.BorderLayout.LINE_START);

        Pnl_MainContainer.setLayout(new java.awt.BorderLayout());
        getContentPane().add(Pnl_MainContainer, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(413, 517));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewActionPerformed
        if(pnl_VehicleAreaOp == null)
        {
            pnl_VehicleAreaOp = new Pnl_VehicleAreaOp();
            //Llamando al panel
        } //Empiezo a crear el objeto a partir de presinar el botón, si no existe nada.
       
        
       //Necesito usar un método en donde el mahe(en el Frame principal), me permita aparecerlo en el MainContainer(Este se considera un componente):
       addComponent(pnl_VehicleAreaOp);
    }//GEN-LAST:event_btn_NewActionPerformed

    private void addComponent(JComponent component)
    {
        //Borra si existe algo ya creado para no saturar la RAM
       Pnl_MainContainer.removeAll();
       //A partir de aquí; estoy diciendo que los muestre
       Pnl_MainContainer.add(component, BorderLayout.CENTER);
       //Para hacer que se acomode, dentro del MainContainer; requiere de un borderLayout(no el que está especificado aquí; sino que, necesita ser añadidio desde Design.
       //Pnl_MainContainer no fue inicializado (private_void_xxxx), porque ya existe como tal (mirar en la parte inferior
       //hasta  abaaaajooo)
       
       //Finalizo con
       validate();
       repaint();
       //Son los que ponen la tinta para pintar uwu
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_VehicleApp_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_VehicleApp_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_VehicleApp_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_VehicleApp_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_VehicleApp_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pnl_MainContainer;
    private javax.swing.JPanel Pnl_SubContainer;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_New;
    private javax.swing.JButton btn_Search;
    // End of variables declaration//GEN-END:variables
}
